[[servers]]
host = "ldap-m1.chem.wisc.edu"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "cn=admin,dc=grafana,dc=org"
search_filter = "(cn=%s)"
search_base_dns = ["dc=grafana,dc=org"]
